### ISSUE TITLE
Persistence setting not working

### ISSUE THREAD

**Issue by syepes** [pyroscope-io/helm-chart#90]
I have been trying to deploy pyroscope with persistence but as the  container is running as non-root (101), its not able to create folder in the mounted volume. This even with the securityContext settings.

```
persistence:
  enabled: true
  size: 16Gi
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  finalizers:
    - kubernetes.io/pvc-protection
```

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/333081/194519337-e2cac400-ebe7-4cc3-a323-c674e5dd1aad.png">

I have managed to resolved the issue by adding the below initContainer to the deployment

```
      initContainers:
      - name: volume-mount-fix
        command:
        - sh
        - -c
        - chmod 777 /var/lib/pyroscope && chown -R 101:101 /var/lib/pyroscope
        image: busybox
        volumeMounts:
        - name: storage
          mountPath: /var/lib/pyroscope
```

Hope this can be added in the official chart or at least the option of customizing the initContainers section.
